const make = ({ id, set, step, specialty, title, clinicalCase, question, options, answer, explanation, feedback, source, tags }) => ({
  id,
  caseSet: set,
  step,
  specialty,
  difficulty: 4,
  source,
  sourceMode: "original-from-summary",
  tags,
  title,
  case: clinicalCase,
  question,
  options,
  answer,
  explanation,
  optionFeedback: feedback,
});

const hypothyroidCase = `Mujer de 39 años con antecedente de macroadenoma hipofisario tratado con cirugía y radioterapia. Consulta por fatiga, estreñimiento e intolerancia al frío. Toma biotina por caída del cabello. Laboratorios: TSH 2.1 mUI/L, T4 libre 0.45 ng/dL, sodio 132 mEq/L. Refiere amenorrea y episodios de mareo al ponerse de pie.`;
const noduleCase = `Mujer de 46 años con nódulo tiroideo de 17 mm detectado incidentalmente. El ultrasonido muestra lesión sólida, marcadamente hipoecoica, más alta que ancha, con márgenes irregulares y microcalcificaciones; se clasifica EU-TIRADS 5. No hay síntomas compresivos. TSH 1.8 mUI/L. Se realiza PAAF y la citología se informa Bethesda II.`;
const thyroiditisCase = `Mujer de 31 años, cuatro meses después del parto, con palpitaciones, ansiedad y pérdida de 4 kg. No tiene dolor cervical ni orbitopatía. TSH <0.01 mUI/L, T4 libre elevada, anti-TPO positivos. El Doppler muestra vascularidad no aumentada. Está lactando.`;
const hyperthyroidCase = `Mujer de 27 años con enfermedad de Graves conocida y embarazo de 8 semanas. Suspendió metimazol al enterarse del embarazo. Presenta temblor, taquicardia y pérdida de peso; T4 libre 2.2 veces por arriba del límite superior. TRAb positivos. No hay datos de tormenta tiroidea.`;
const cancerCase = `Hombre de 36 años con nódulo tiroideo y adenopatía lateral. La PAAF ganglionar es sugestiva de neoplasia tiroidea, pero la citología es poco celular. Calcitonina sérica elevada, CEA elevado y tiroglobulina sérica no concluyente. Su padre fue operado por feocromocitoma.`;
const phCase = `Mujer de 48 años con esclerosis sistémica, disnea progresiva, presíncope y edema. Ecocardiograma: dilatación del ventrículo derecho y alta probabilidad de hipertensión pulmonar. Cateterismo derecho: mPAP 34 mmHg, PAWP 10 mmHg, PVR 5.4 UW, gasto cardiaco reducido. Clase funcional OMS III.`;
const ctephCase = `Hombre de 61 años con disnea persistente 9 meses después de una embolia pulmonar tratada. Ecocardiograma con sobrecarga del ventrículo derecho. El gammagrama ventilación/perfusión muestra defectos segmentarios de perfusión no concordantes; la angio-TC sugiere bandas y estenosis crónicas.`;
const resistantCase = `Hombre de 54 años con presión arterial de 166/98 mmHg pese a losartán, amlodipino e hidroclorotiazida. Refiere apego adecuado. En casa promedia 162/94 mmHg. Potasio 3.1 mEq/L, bicarbonato 30 mEq/L, creatinina normal. No usa AINE ni descongestionantes.`;

const latestWordAdvancedCases = [
  make({id:9201,set:"WORD-HYPO-01",step:1,specialty:"Endocrinología",title:"Hipotiroidismo central",clinicalCase:hypothyroidCase,question:"¿Cuál es la interpretación más probable del perfil tiroideo?",options:["Eutiroidismo porque la TSH es normal","Hipotiroidismo central","Hipotiroidismo primario subclínico","Síndrome de T3 baja aislado"],answer:1,explanation:"Una T4 libre baja con TSH inapropiadamente normal en una paciente con enfermedad hipofisaria indica hipotiroidismo central.",feedback:["La TSH normal no excluye hipotiroidismo central.","Correcta: la TSH es biológicamente o cuantitativamente inapropiada para la T4 libre baja.","En el primario la TSH debería estar elevada.","La alteración central es T4 libre baja, no solo T3."],source:"Resumen_extenso_hipotiroidismo_JAMA_2025.docx",tags:["Hipotiroidismo central","Hipófisis"]}),
  make({id:9202,set:"WORD-HYPO-01",step:2,specialty:"Endocrinología",title:"Evaluación antes de levotiroxina",clinicalCase:hypothyroidCase,question:"Antes de iniciar levotiroxina, ¿qué deficiencia debe descartarse o tratarse primero?",options:["Deficiencia de vitamina D","Insuficiencia suprarrenal central","Deficiencia de hierro","Hiperaldosteronismo"],answer:1,explanation:"La hormona tiroidea puede aumentar la depuración y demanda de cortisol y precipitar crisis suprarrenal si existe insuficiencia no tratada.",feedback:["No condiciona una emergencia por iniciar levotiroxina.","Correcta: evaluar cortisol y administrar glucocorticoide cuando la sospecha sea relevante.","Puede coexistir, pero no tiene esta prioridad fisiológica.","El contexto sugiere déficit hipofisario, no exceso de aldosterona."],source:"Resumen_extenso_hipotiroidismo_JAMA_2025.docx",tags:["Insuficiencia suprarrenal","Levotiroxina"]}),
  make({id:9203,set:"WORD-HYPO-01",step:3,specialty:"Endocrinología",title:"Seguimiento del hipotiroidismo central",clinicalCase:hypothyroidCase,question:"Después de iniciar tratamiento, ¿qué parámetro debe guiar el ajuste?",options:["TSH hacia 1 mUI/L","T4 libre, habitualmente en la mitad superior del intervalo","T3 reversa","Anti-TPO seriados"],answer:1,explanation:"En hipotiroidismo central la TSH no es fiable para titular; se utiliza T4 libre junto con la respuesta clínica.",feedback:["La TSH puede permanecer baja o normal pese a sustitución insuficiente.","Correcta.","No es una prueba de seguimiento rutinaria.","Los anticuerpos establecen etiología, no dosis."],source:"Resumen_extenso_hipotiroidismo_JAMA_2025.docx",tags:["Seguimiento","T4 libre"]}),
  make({id:9204,set:"WORD-HYPO-01",step:4,specialty:"Endocrinología",title:"Interacción con levotiroxina",clinicalCase:hypothyroidCase+" Meses después requiere dosis crecientes; toma la tableta junto con desayuno, calcio y hierro.",question:"¿Cuál es la primera intervención?",options:["Añadir liotironina","Separar levotiroxina de calcio y hierro al menos 4 horas","Duplicar la dosis sin revisar administración","Cambiar a hormona tiroidea desecada"],answer:1,explanation:"La absorción disminuye con alimentos, calcio y hierro; primero debe corregirse la forma de administración.",feedback:["No corrige la causa de malabsorción y no es primera línea.","Correcta.","Aumenta riesgo de sobretratamiento si después mejora la absorción.","No es tratamiento estándar."],source:"Resumen_extenso_hipotiroidismo_JAMA_2025.docx",tags:["Absorción","Calcio","Hierro"]}),

  make({id:9205,set:"WORD-NODULE-01",step:1,specialty:"Endocrinología",title:"Discordancia ecografía-citología",clinicalCase:noduleCase,question:"¿Cuál es la conducta más apropiada ante esta discordancia?",options:["Dar de alta por Bethesda II","Repetir evaluación dirigida y PAAF porque persiste alta sospecha ecográfica","Iniciar levotiroxina supresora","Realizar gammagrafía pese a TSH normal como único estudio"],answer:1,explanation:"Una citología benigna no debe ignorar un patrón EU-TIRADS 5; se revisa calidad, correlación y suele repetirse la PAAF.",feedback:["Bethesda II tiene bajo riesgo, pero la discordancia exige resolución.","Correcta.","La supresión con levotiroxina no se recomienda en eutiroideos.","La gammagrafía se prioriza con TSH baja o sospecha de autonomía."],source:"Resumen_extenso_guia_europea_nodulo_tiroideo_2023.docx",tags:["EU-TIRADS 5","Bethesda II"]}),
  make({id:9206,set:"WORD-NODULE-01",step:2,specialty:"Endocrinología",title:"PAAF no diagnóstica repetida",clinicalCase:noduleCase+" Dos PAAF posteriores resultan no diagnósticas pese a técnica adecuada.",question:"¿Qué procedimiento puede considerarse como segunda línea?",options:["Biopsia con aguja gruesa","PET de rutina","Tiroidectomía total automática","Observación sin nueva evaluación"],answer:0,explanation:"La biopsia con aguja gruesa puede ayudar tras PAAF repetidamente no diagnóstica y en sospecha de linfoma o tumor poco diferenciado.",feedback:["Correcta en escenarios seleccionados.","No es la prueba de rescate rutinaria.","La cirugía depende del riesgo y no es automática.","Mantendría sin resolver una lesión de alta sospecha."],source:"Resumen_extenso_guia_europea_nodulo_tiroideo_2023.docx",tags:["Biopsia gruesa","PAAF"]}),
  make({id:9207,set:"WORD-NODULE-01",step:3,specialty:"Endocrinología",title:"Nódulo hiperfuncionante",clinicalCase:"Paciente de 63 años con TSH suprimida y nódulo de 22 mm. La gammagrafía demuestra captación focal intensa con supresión del resto del parénquima; el ultrasonido no muestra ganglios sospechosos.",question:"¿Cuál afirmación es correcta?",options:["Todo nódulo caliente requiere PAAF","Generalmente no requiere PAAF por su muy bajo riesgo de malignidad","Debe tratarse con levotiroxina supresora","La gammagrafía está indicada solo si la TSH está elevada"],answer:1,explanation:"Los nódulos hiperfuncionantes generalmente no se biopsian, salvo hallazgos discordantes de alto riesgo.",feedback:["La función autónoma modifica la indicación de PAAF.","Correcta.","Empeoraría la tirotoxicosis.","La indicación clásica es TSH baja."],source:"Resumen_extenso_guia_europea_nodulo_tiroideo_2023.docx",tags:["Nódulo autónomo","Gammagrafía"]}),
  make({id:9208,set:"WORD-NODULE-01",step:4,specialty:"Endocrinología",title:"Bethesda III",clinicalCase:"Mujer de 42 años con nódulo EU-TIRADS 4 de 18 mm. La PAAF reporta Bethesda III. No hay adenopatías, radiación previa ni antecedente familiar.",question:"¿Cuál es el siguiente enfoque más razonable?",options:["Tiroidectomía total obligatoria","Integrar riesgo ecográfico y clínico, repetir PAAF y considerar prueba molecular","Descartar malignidad porque no es Bethesda VI","Yodo radiactivo ablativo"],answer:1,explanation:"Bethesda III no obliga a cirugía; debe resolverse con integración clínica-ecográfica, repetición de PAAF y, donde esté disponible, análisis molecular.",feedback:["Sobretrata muchos nódulos indeterminados.","Correcta.","El riesgo no es cero.","No trata un diagnóstico citológico indeterminado."],source:"Resumen_extenso_guia_europea_nodulo_tiroideo_2023.docx",tags:["Bethesda III","Molecular"]}),

  make({id:9209,set:"WORD-THYROIDITIS-01",step:1,specialty:"Endocrinología",title:"Tiroiditis posparto",clinicalCase:thyroiditisCase,question:"¿Cuál es el diagnóstico más probable?",options:["Enfermedad de Graves","Tiroiditis posparto en fase tirotóxica","Adenoma tóxico","Tirotoxicosis facticia"],answer:1,explanation:"El momento posparto, anti-TPO, ausencia de dolor y vascularidad no aumentada apoyan tiroiditis posparto destructiva.",feedback:["Graves suele mostrar TRAb, hipervascularidad y captación aumentada.","Correcta.","Se esperaría un nódulo autónomo.","La tiroglobulina y la historia farmacológica ayudarían, pero el contexto favorece posparto."],source:"Tiroiditis_resumen_extenso.docx",tags:["Posparto","Tirotoxicosis"]}),
  make({id:9210,set:"WORD-THYROIDITIS-01",step:2,specialty:"Endocrinología",title:"Tratamiento de fase destructiva",clinicalCase:thyroiditisCase,question:"¿Cuál es el tratamiento más apropiado para sus palpitaciones?",options:["Metimazol","Propiltiouracilo","Betabloqueador compatible con lactancia","Yodo radiactivo"],answer:2,explanation:"En la tiroiditis destructiva no hay síntesis aumentada; se trata sintomáticamente con betabloqueador cuando se necesita.",feedback:["Bloquea síntesis y no corrige liberación de hormona almacenada.","Tiene el mismo problema y mayor toxicidad hepática.","Correcta; debe individualizarse el fármaco y la dosis.","Está contraindicado durante la lactancia."],source:"Tiroiditis_resumen_extenso.docx",tags:["Betabloqueador","Lactancia"]}),
  make({id:9211,set:"WORD-THYROIDITIS-01",step:3,specialty:"Endocrinología",title:"Evolución trifásica",clinicalCase:thyroiditisCase+" Cuatro meses después presenta cansancio; TSH 12 mUI/L y T4 libre baja.",question:"¿Cuál es la conducta más apropiada?",options:["Asumir hipotiroidismo permanente en todos los casos","Considerar levotiroxina si es sintomática o planea embarazo y reevaluar posteriormente","Iniciar metimazol","Solicitar yodo radiactivo terapéutico"],answer:1,explanation:"La fase hipotiroidea puede ser transitoria; se trata según síntomas, intensidad y planes reproductivos, con reevaluación posterior.",feedback:["Una proporción recupera eutiroidismo.","Correcta.","Empeoraría el hipotiroidismo.","No tiene indicación en una tiroiditis destructiva."],source:"Tiroiditis_resumen_extenso.docx",tags:["Hipotiroidismo posparto","Levotiroxina"]}),
  make({id:9212,set:"WORD-THYROIDITIS-01",step:4,specialty:"Endocrinología",title:"De Quervain",clinicalCase:"Paciente de 38 años con fiebre, dolor cervical anterior que irradia a mandíbula, tiroides muy dolorosa, VSG y PCR elevadas, TSH suprimida y captación tiroidea baja.",question:"Si el dolor es intenso y no responde a AINE, ¿cuál es el siguiente tratamiento?",options:["Glucocorticoide","Metimazol a dosis alta","Levotiroxina supresora","Antibiótico por seis semanas en todos"],answer:0,explanation:"La tiroiditis subaguda dolorosa se trata con AINE; los glucocorticoides se reservan para dolor intenso o refractario.",feedback:["Correcta.","No hay hiperproducción hormonal.","No controla la inflamación y puede causar tirotoxicosis.","La etiología habitual no es bacteriana."],source:"Tiroiditis_resumen_extenso.docx",tags:["De Quervain","VSG"]}),

  make({id:9213,set:"WORD-GRAVES-PREG-01",step:1,specialty:"Endocrinología",title:"Graves en primer trimestre",clinicalCase:hyperthyroidCase,question:"¿Cuál es el antitiroideo preferido durante este periodo?",options:["Metimazol","Propiltiouracilo","Yodo radiactivo","Levotiroxina"],answer:1,explanation:"Durante el primer trimestre se prefiere PTU por el patrón de embriopatía asociado a metimazol; después suele considerarse cambio a metimazol.",feedback:["Es primera línea fuera del primer trimestre, pero su embriopatía es más característica.","Correcta.","Está contraindicado en embarazo.","No trata Graves y empeoraría la tirotoxicosis."],source:"Hipertiroidismo- resumen extenso y detallado.docx",tags:["Graves","Embarazo","PTU"]}),
  make({id:9214,set:"WORD-GRAVES-PREG-01",step:2,specialty:"Endocrinología",title:"Meta terapéutica en embarazo",clinicalCase:hyperthyroidCase,question:"¿Cuál es el principio de ajuste de dosis durante el embarazo?",options:["Normalizar TSH con dosis máximas","Usar la dosis mínima que mantenga T4 libre cerca del límite superior o discretamente elevada","Combinar antitiroideo con levotiroxina","Suspender vigilancia fetal si mejora la madre"],answer:1,explanation:"Se busca evitar hipotiroidismo fetal usando la menor dosis efectiva; la TSH puede permanecer suprimida.",feedback:["Puede provocar hipotiroidismo fetal.","Correcta.","El bloqueo y reemplazo aumenta exposición fetal y no se recomienda.","TRAb y control materno pueden requerir vigilancia fetal."],source:"Hipertiroidismo- resumen extenso y detallado.docx",tags:["Embarazo","T4 libre"]}),
  make({id:9215,set:"WORD-GRAVES-PREG-01",step:3,specialty:"Endocrinología",title:"TRAb y riesgo fetal",clinicalCase:hyperthyroidCase+" En la segunda mitad del embarazo los TRAb permanecen muy elevados.",question:"¿Qué implicación tiene este hallazgo?",options:["Descarta afectación fetal","Justifica vigilancia por hipertiroidismo fetal o neonatal","Obliga a yodo radiactivo materno","Solo predice hipotiroidismo materno"],answer:1,explanation:"Los TRAb atraviesan la placenta y pueden estimular la tiroides fetal, incluso después de tratamiento definitivo materno previo.",feedback:["Los anticuerpos sí cruzan la placenta.","Correcta.","El radioyodo está contraindicado.","El riesgo relevante incluye tirotoxicosis fetal y neonatal."],source:"Hipertiroidismo- resumen extenso y detallado.docx",tags:["TRAb","Feto"]}),
  make({id:9216,set:"WORD-GRAVES-PREG-01",step:4,specialty:"Endocrinología",title:"Cirugía durante embarazo",clinicalCase:hyperthyroidCase+" Desarrolla reacción grave a ambos antitiroideos y requiere tratamiento definitivo durante el embarazo.",question:"¿Cuál es la opción y el momento preferidos?",options:["Yodo radioactivo en el primer trimestre","Tiroidectomía durante el segundo trimestre","Tiroidectomía durante trabajo de parto","Observación sin tratamiento"],answer:1,explanation:"Si la cirugía es imprescindible, el segundo trimestre ofrece el mejor balance entre riesgos maternos y fetales.",feedback:["Contraindicado durante embarazo y lactancia.","Correcta.","Añade riesgo obstétrico y anestésico.","La tirotoxicosis manifiesta no controlada tiene riesgos importantes."],source:"Hipertiroidismo- resumen extenso y detallado.docx",tags:["Tiroidectomía","Segundo trimestre"]}),

  make({id:9217,set:"WORD-MTC-01",step:1,specialty:"Endocrinología",title:"Carcinoma medular",clinicalCase:cancerCase,question:"¿Cuál es el diagnóstico más probable?",options:["Carcinoma papilar","Carcinoma medular","Carcinoma folicular","Linfoma tiroideo"],answer:1,explanation:"La calcitonina elevada y el antecedente familiar de feocromocitoma sugieren carcinoma medular asociado a MEN2.",feedback:["Produce tiroglobulina y suele diseminar por vía linfática, pero no calcitonina.","Correcta.","Se diagnostica por invasión capsular o vascular y no produce calcitonina.","No explica el patrón endocrino familiar."],source:"resúmen Cáncer de tiroides.docx",tags:["Medular","MEN2"]}),
  make({id:9218,set:"WORD-MTC-01",step:2,specialty:"Endocrinología",title:"Prueba genética en carcinoma medular",clinicalCase:cancerCase,question:"¿Qué estudio debe solicitarse aunque parezca un caso esporádico?",options:["Mutación germinal RET","HLA-B27","JAK2 V617F","BRCA1 aislado"],answer:0,explanation:"Todo carcinoma medular requiere evaluación de RET germinal para identificar enfermedad hereditaria y orientar a familiares.",feedback:["Correcta.","No se relaciona con MEN2.","Corresponde a neoplasias mieloproliferativas.","No es el gen causal típico del carcinoma medular."],source:"resúmen Cáncer de tiroides.docx",tags:["RET","Genética"]}),
  make({id:9219,set:"WORD-MTC-01",step:3,specialty:"Endocrinología",title:"Preparación antes de cirugía medular",clinicalCase:cancerCase,"question":"Antes de la tiroidectomía, ¿qué condición asociada debe excluirse de forma prioritaria?","options":["Feocromocitoma","Enfermedad celíaca","Hiperprolactinemia","Acromegalia"],"answer":0,"explanation":"En MEN2 debe descartarse feocromocitoma antes de operar la tiroides para evitar una crisis catecolaminérgica perioperatoria.","feedback":["Correcta y potencialmente vital.","Puede coexistir con autoinmunidad, pero no define esta prioridad.","No es componente de MEN2.","No es componente típico de MEN2."],source:"resúmen Cáncer de tiroides.docx",tags:["Feocromocitoma","Preoperatorio"]}),
  make({id:9220,set:"WORD-MTC-01",step:4,specialty:"Endocrinología",title:"Seguimiento de carcinoma medular",clinicalCase:cancerCase+" Después del tratamiento persisten calcitonina y CEA detectables.",question:"¿Qué dato cinético indica comportamiento más agresivo?",options:["Duplicación de calcitonina menor de un año","Calcitonina estable durante diez años","Tiroglobulina indetectable","TSH de 2 mUI/L"],answer:0,explanation:"Un tiempo de duplicación corto de calcitonina, especialmente menor de un año, se asocia con progresión y peor pronóstico.",feedback:["Correcta.","Sugiere biología más indolente.","No es marcador del carcinoma medular.","La TSH no guía la biología de células C."],source:"resúmen Cáncer de tiroides.docx",tags:["Calcitonina","Pronóstico"]}),

  make({id:9221,set:"WORD-PH-01",step:1,specialty:"Neumología",title:"Hemodinámica precapilar",clinicalCase:phCase,question:"¿Cómo se clasifica el patrón hemodinámico?",options:["HP postcapilar aislada","HP precapilar","HP postcapilar combinada","No cumple definición de HP"],answer:1,explanation:"mPAP >20, PAWP ≤15 y PVR >2 UW definen hipertensión pulmonar precapilar.",feedback:["Requeriría PAWP >15 y PVR ≤2.","Correcta.","Requeriría PAWP >15 y PVR >2.","La mPAP está elevada."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["HAP","Hemodinámica"]}),
  make({id:9222,set:"WORD-PH-01",step:2,specialty:"Neumología",title:"Grupo clínico de HAP",clinicalCase:phCase,question:"En ausencia de enfermedad pulmonar o tromboembólica, ¿a qué grupo pertenece?",options:["Grupo 1, HAP asociada a esclerosis sistémica","Grupo 2","Grupo 3","Grupo 5"],answer:0,explanation:"La HAP asociada a enfermedad del tejido conectivo, incluida esclerosis sistémica, pertenece al grupo 1.",feedback:["Correcta.","Es por cardiopatía izquierda.","Es por enfermedad pulmonar o hipoxia.","Agrupa mecanismos inciertos o multifactoriales."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["Esclerosis sistémica","Grupo 1"]}),
  make({id:9223,set:"WORD-PH-01",step:3,specialty:"Neumología",title:"Tratamiento inicial de HAP",clinicalCase:phCase+" La estratificación integral no muestra criterios de alto riesgo que obliguen a prostaciclina parenteral inmediata.",question:"¿Cuál es el tratamiento inicial preferido?",options:["Macitentán más tadalafil","Sildenafil más riociguat","Oxígeno como única terapia","Betabloqueador más verapamilo"],answer:0,explanation:"En HAP de riesgo bajo o intermedio se recomienda combinación inicial de un ERA y un inhibidor PDE5.",feedback:["Correcta: combina dos vías terapéuticas.","La combinación riociguat-PDE5i está contraindicada por hipotensión.","El oxígeno se usa si hay hipoxemia, pero no sustituye terapia específica.","Los calcioantagonistas solo se usan en respondedores vasorreactivos seleccionados."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["ERA","PDE5i"]}),
  make({id:9224,set:"WORD-PH-01",step:4,specialty:"Neumología",title:"Falla terapéutica en HAP",clinicalCase:phCase+" Tras terapia combinada permanece en riesgo intermedio-alto, con deterioro del ventrículo derecho.",question:"¿Cuál es el siguiente principio terapéutico?",options:["Desescalar a monoterapia","Escalar la vía de prostaciclina y valorar referencia para trasplante según evolución","Añadir riociguat al sildenafil","Suspender toda terapia específica"],answer:1,explanation:"La persistencia de riesgo intermedio-alto exige escalamiento, con terapia de la vía de prostaciclina y evaluación experta.",feedback:["No persigue la meta de riesgo bajo.","Correcta.","La combinación está contraindicada.","Aumentaría el riesgo de progresión."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["Prostaciclina","Riesgo"]}),

  make({id:9225,set:"WORD-CTEPH-01",step:1,specialty:"Neumología",title:"Tamizaje de CTEPH",clinicalCase:ctephCase,question:"¿Cuál es la prueba de detección más sensible para CTEPH?",options:["Gammagrama ventilación/perfusión","Radiografía de tórax","Espirometría","Dímero D aislado"],answer:0,explanation:"Un gammagrama V/Q normal prácticamente excluye CTEPH; es la prueba de detección recomendada.",feedback:["Correcta.","Puede ser anormal pero no excluye la enfermedad.","Evalúa mecánica ventilatoria.","No descarta trombo organizado crónico."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["CTEPH","V/Q"]}),
  make({id:9226,set:"WORD-CTEPH-01",step:2,specialty:"Neumología",title:"Tratamiento de CTEPH operable",clinicalCase:ctephCase+" Un equipo experto concluye que las lesiones son accesibles quirúrgicamente.",question:"¿Cuál es el tratamiento de elección?",options:["Endarterectomía pulmonar","Trombólisis sistémica crónica","Sildenafil como sustituto de cirugía","Filtro de vena cava como tratamiento definitivo"],answer:0,explanation:"La endarterectomía pulmonar es potencialmente curativa y constituye el tratamiento de elección en CTEPH operable.",feedback:["Correcta.","No remueve material fibrótico organizado y tiene riesgo hemorrágico.","No debe sustituir una opción curativa.","No trata la obstrucción pulmonar establecida."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["Endarterectomía","Operabilidad"]}),
  make({id:9227,set:"WORD-CTEPH-01",step:3,specialty:"Neumología",title:"CTEPH inoperable",clinicalCase:ctephCase+" En otro paciente, el equipo multidisciplinario determina enfermedad distal inoperable con síntomas persistentes.",question:"¿Qué opciones específicas deben considerarse?",options:["Angioplastia pulmonar con balón y/o riociguat","Trombolítico oral indefinido","Solo observación","Trasplante renal"],answer:0,explanation:"En CTEPH inoperable se consideran BPA y riociguat, idealmente en centros expertos.",feedback:["Correcta.","No existe trombolítico oral crónico indicado para material organizado.","La enfermedad sintomática requiere manejo activo.","No tiene relación con la fisiopatología."],source:"RESUMEN HIPERTENSIÓN PULMONAR guia ESC 2022.docx",tags:["BPA","Riociguat"]}),

  make({id:9228,set:"WORD-RESISTANT-01",step:1,specialty:"Cardiología",title:"Hipertensión resistente con hipopotasemia",clinicalCase:resistantCase,question:"¿Cuál es la causa secundaria que debe buscarse prioritariamente?",options:["Hiperaldosteronismo primario","Feocromocitoma como única posibilidad","Coartación de aorta","Hipotiroidismo central"],answer:0,explanation:"HTA resistente, hipopotasemia y alcalosis metabólica son pistas clásicas de hiperaldosteronismo primario.",feedback:["Correcta.","Suele producir síntomas catecolaminérgicos y no explica típicamente hipopotasemia persistente.","Es menos congruente con el perfil bioquímico.","No produce este patrón mineralocorticoide."],source:"resumen GUÍA AHA ACC 2025 DE HIPERTENSIÓN ARTERIAL.docx",tags:["HTA resistente","Aldosterona"]}),
  make({id:9229,set:"WORD-RESISTANT-01",step:2,specialty:"Cardiología",title:"Tamizaje de hiperaldosteronismo",clinicalCase:resistantCase,question:"¿Cuál es el estudio inicial de tamizaje?",options:["Relación aldosterona/renina","Metanefrinas urinarias como única prueba","Cortisol libre urinario en todos","Angio-TC renal antes de pruebas hormonales"],answer:0,explanation:"La relación aldosterona-renina es la prueba inicial, interpretada con potasio, fármacos y condiciones de toma.",feedback:["Correcta.","Corresponde a feocromocitoma.","Se usa ante sospecha de hipercortisolismo.","La imagen no sustituye la evaluación bioquímica."],source:"resumen GUÍA AHA ACC 2025 DE HIPERTENSIÓN ARTERIAL.docx",tags:["ARR","Tamizaje"]}),
  make({id:9230,set:"WORD-RESISTANT-01",step:3,specialty:"Cardiología",title:"Cuarto fármaco en HTA resistente",clinicalCase:"Paciente con HTA resistente verdadera confirmada por mediciones domiciliarias. Recibe IECA/ARA-II, calcioantagonista dihidropiridínico y diurético tipo tiazida a dosis adecuadas. TFG 68 mL/min y potasio 4.1 mEq/L; no se identifica causa secundaria corregible.",question:"¿Cuál es el cuarto fármaco preferido?",options:["Espironolactona","Clonidina como primera elección","Aliskireno combinado con IECA","Doxazosina antes que antagonista mineralocorticoide"],answer:0,explanation:"Un antagonista del receptor mineralocorticoide, habitualmente espironolactona, es el cuarto agente preferido si función renal y potasio lo permiten.",feedback:["Correcta; requiere monitorización de potasio y función renal.","Puede utilizarse después en casos seleccionados, pero no suele ser cuarta línea preferida.","La doble inhibición del SRAA aumenta eventos adversos.","Los alfa bloqueadores no superan a espironolactona como estrategia general."],source:"resumen GUÍA AHA ACC 2025 DE HIPERTENSIÓN ARTERIAL.docx",tags:["Espironolactona","Cuarta línea"]}),
];

export default latestWordAdvancedCases;
